#!/usr/bin/env python3
"""Regenerate deterministic binary64 vectors using correctly rounded MPFR at 256 bits.

Requires the host MPFR shared library only when regenerating. Normal tests use
checked-in vectors and have no MPFR/Python dependency. No third-party Python
packages are required. Run from any directory: python3 tests/math_reference.py.
"""

import ctypes
import ctypes.util
import math
import os
from pathlib import Path
import random
import struct
import subprocess


class Mpfr(ctypes.Structure):
    _fields_ = [
        ("precision", ctypes.c_long),
        ("sign", ctypes.c_int),
        ("exponent", ctypes.c_long),
        ("limbs", ctypes.POINTER(ctypes.c_ulong)),
    ]


library = ctypes.CDLL(ctypes.util.find_library("mpfr"))
pointer = ctypes.POINTER(Mpfr)
library.mpfr_init2.argtypes = [pointer, ctypes.c_long]
library.mpfr_set_d.argtypes = [pointer, ctypes.c_double, ctypes.c_int]
library.mpfr_get_d.argtypes = [pointer, ctypes.c_int]
library.mpfr_get_d.restype = ctypes.c_double
library.mpfr_clear.argtypes = [pointer]
operand = Mpfr()
second_operand = Mpfr()
result = Mpfr()
library.mpfr_init2(ctypes.byref(operand), 256)
library.mpfr_init2(ctypes.byref(second_operand), 256)
library.mpfr_init2(ctypes.byref(result), 256)


def reference(name, value):
    function = getattr(library, "mpfr_" + name)
    if isinstance(value, tuple):
        function.argtypes = [pointer, pointer, pointer, ctypes.c_int]
        library.mpfr_set_d(ctypes.byref(operand), value[0], 0)
        library.mpfr_set_d(ctypes.byref(second_operand), value[1], 0)
        function(ctypes.byref(result), ctypes.byref(operand), ctypes.byref(second_operand), 0)
    else:
        function.argtypes = [pointer, pointer, ctypes.c_int]
        library.mpfr_set_d(ctypes.byref(operand), value, 0)
        function(ctypes.byref(result), ctypes.byref(operand), 0)
    return library.mpfr_get_d(ctypes.byref(result), 0)


def bits(value):
    return struct.unpack(">Q", struct.pack(">d", value))[0]


def from_bits(value):
    return struct.unpack(">d", struct.pack(">Q", value))[0]


rng = random.Random(0xD0D0_4D415448)
positive = [from_bits(i) for i in [1, 2, 3, (1 << 52) - 1, 1 << 52, 0x7FEFFFFFFFFFFFFF]]
positive += [math.nextafter(1.0, 0.0), 1.0, math.nextafter(1.0, math.inf), 2.0, 3.0, 4.0]
# Sample the complete normal exponent range, both parities, and varying significands.
positive += [from_bits((min(2046, exponent + ((exponent // 4) % 4)) << 52) | rng.getrandbits(52)) for exponent in range(1, 2047, 4)]
angles = [0.0, -0.0, 0.1, -0.1, math.pi / 4, math.pi / 2, math.pi, math.tau, 1e20, 1e100, 1e300]
angles += [value * (-1.0 if i % 2 else 1.0) for i, value in enumerate(positive)]
for index in [1, 2, 3, 8, 100, 100000, 1000000000]:
    center = index * math.pi / 2
    angles.extend([math.nextafter(center, -math.inf), center, math.nextafter(center, math.inf)])
exponents = [-745.0, -744.0, -710.0, -709.0, -1.0, -1e-20, -0.0, 0.0, 1e-20, 1.0, 709.0, 709.7827128933839]
exponents += [-745.0 + 1454.0 * i / 511 for i in range(512)]
unit = [-1.0, -0.0, 0.0, 1.0, math.nextafter(1.0, 0.0), math.nextafter(-1.0, 0.0)]
unit += [-1.0 + 2.0 * i / 511 for i in range(512)]
small = [-0.499, -1e-8, -1e-20, -0.0, 0.0, 1e-20, 1e-8, 0.499]
small += [-0.499 + 0.998 * i / 127 for i in range(128)]

powers = [(value, [-1.5, -0.75, -0.1, 0.1, 0.25, 0.75, 1.5][i % 7]) for i, value in enumerate(positive)]
powers = [pair for pair in powers if math.isfinite(reference("pow", pair))]
norms = [(value, positive[-1 - i]) for i, value in enumerate(positive)]
quadrants = [(value, -positive[-1 - i] if i % 2 else positive[-1 - i]) for i, value in enumerate(positive)]

# These are conservative regression bounds, not proofs of correct rounding.
cases = [
    ("sqrt", "math", positive, 2e-15, 0.0, True),
    ("cbrt", "math", angles, 3e-15, 0.0, False),
    ("log", "math", positive, 3e-15, 0.0, True),
    ("log2", "math", positive, 4e-15, 0.0, True),
    ("log10", "math", positive, 4e-15, 0.0, True),
    ("exp", "math", exponents, 3e-15, from_bits(2), True),
    ("expm1", "math", small, 3e-15, 0.0, True),
    ("log1p", "math", small, 4e-15, 0.0, True),
    ("sin", "trig", angles, 0.0, 3e-15, True),
    ("cos", "trig", angles, 0.0, 3e-15, True),
    ("tan", "trig", angles, 2e-14, from_bits(2), True),
    ("atan", "trig", angles, 0.0, 3e-15, False),
    ("asin", "trig", unit, 0.0, 3e-15, True),
    ("acos", "trig", unit, 0.0, 3e-15, True),
    ("exp2", "math", [-1075.0 + 2098.5 * i / 511 for i in range(512)], 4e-15, from_bits(2), True),
    ("pow", "math", powers, 3e-13, from_bits(2), True),
    ("hypot", "math", norms, 3e-15, from_bits(2), False),
    ("atan2", "trig", quadrants, 0.0, 3e-15, False),
]
lines = [
    "// Generated by tests/math_reference.py; MPFR 256-bit, round-to-nearest-even.",
    "// Deterministic exponent-stratified cases plus reduction and endpoint boundaries.",
    "package math_reference",
    'import "std/math"',
    'import "std/math/trig"',
    "",
    "fn close(actual: f64, expected: f64, relative: f64, absolute: f64) -> bool {",
    "    if actual == expected {",
    "        if actual == 0.0 { return math.to_bits(actual) == math.to_bits(expected) }",
    "        return true",
    "    }",
    "    if !math.is_finite(actual) || !math.is_finite(expected) { return false }",
    "    return math.abs(actual - expected) <= relative * math.abs(expected) + absolute",
    "}",
]
for index, (name, module, values, relative, absolute, checked) in enumerate(cases):
    lines.append(f"fn check_{name}() -> bool {{")
    binary = isinstance(values[0], tuple)
    arrays = [("inputs", [value[0] for value in values] if binary else values)]
    if binary:
        arrays.append(("second_inputs", [value[1] for value in values]))
    arrays.append(("expected", [reference(name, value) for value in values]))
    for array_name, entries in arrays:
        lines.append(f"    {array_name} := [")
        for start in range(0, len(entries), 6):
            batch = entries[start:start + 6]
            suffix = "," if start + 6 < len(entries) else "]"
            lines.append("        " + ", ".join(f"0x{bits(value):016x}u64" for value in batch) + suffix)
    lines.append(f"    for i in 0usize..{len(values)} {{")
    arguments = "math.from_bits(inputs[i])"
    if binary:
        arguments += ", math.from_bits(second_inputs[i])"
    call = f"{module}.{name}({arguments})"
    check = f"if !close(value, math.from_bits(expected[i]), {relative!r}, {absolute!r}) {{ return false }}"
    if checked:
        lines.append(f"        match {call} {{ ok(value) => {{ {check} }}, err(_) => {{ return false }} }}")
    else:
        lines.append(f"        value := {call}")
        lines.append(f"        {check}")
    lines += ["    }", "    return true", "}"]
lines.append("fn main() -> i32 {")
for index, (name, *_rest) in enumerate(cases):
    lines.append(f"    if !check_{name}() {{ return {index + 1} }}")
lines += ["    return 0", "}", ""]
for name, *_rest in cases:
    lines += ["@test", f"fn test_{name}_reference() {{", f"    assert(check_{name}(), \"{name} differs from the MPFR reference\")", "}", ""]
path = Path(__file__).resolve().parent / "stdlib" / "math_reference.dodo"
path.write_text("\n".join(lines))
library.mpfr_clear(ctypes.byref(operand))
library.mpfr_clear(ctypes.byref(second_operand))
library.mpfr_clear(ctypes.byref(result))
compiler = Path(os.environ.get("DODO_COMPILER", path.parents[2] / "target/debug/dodo"))
if not compiler.is_file():
    raise SystemExit("Build target/debug/dodo or set DODO_COMPILER to format generated vectors")
subprocess.run([str(compiler), "fmt", str(path)], check=True)
print(f"Wrote {sum(len(case[2]) for case in cases)} MPFR reference cases to {path}")
